server.port: 8091
#server.context.path: /
#server.context.host: 0.0.0.0

app.name: ebean-insight
load.properties: /app/config/insight-config.yaml

ebean.queryPlan.enable: true

##
## Postgres setup - To use local docker instance see src/test/main/StartPostgresDocker.main()
##
ebean:
  dbSchema: ${db_user:ebean_insight}
  migration.run: true

datasource:
  db:
    username: ${db_user:ebean_insight}
    password: ${db_pass:ebean_insight}
    url: jdbc:postgresql://${db_url:localhost:9432}/ebean_insight

