-- extends db partitions
select partition('day', 'gauge_entry', 4);
select partition('day', 'timed_entry', 4);
select partition('day', 'timed_m1', 4);
select partition('day', 'gauge_m1', 4);
select partition('day', 'timed_m10', 4);
select partition('day', 'gauge_m10', 4);
select partition('day', 'timed_m60', 4);
select partition('day', 'gauge_m60', 4);
select partition('day', 'timed_d1', 4);
select partition('day', 'gauge_d1', 4);
