-- apply changes
create table ebean_insight.capture_request (
  id                            integer generated by default as identity not null,
  app_id                        integer not null,
  env_id                        integer,
  requested_at                  timestamptz not null,
  collected_at                  timestamptz,
  version                       integer not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  hash                          varchar not null,
  label                         varchar,
  constraint pk_capture_request primary key (id)
);

-- foreign keys and indices
create index if not exists ix_capture_request_open on ebean_insight.capture_request (collected_at,requested_at);
