-- apply changes
create table ebean_insight.query_plan_change (
  id                            integer generated by default as identity not null,
  app_id                        integer not null,
  env_id                        integer not null,
  from_plan_id                  integer,
  to_plan_id                    integer not null,
  algo                          integer not null,
  from_query_time_micros        bigint,
  to_query_time_micros          bigint not null,
  when_captured                 timestamptz not null,
  detected_at                   timestamptz not null,
  notified_at                   timestamptz,
  version                       integer not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  hash                          varchar not null,
  label                         varchar,
  change_type                   varchar(20) not null,
  from_shape_hash               varchar,
  to_shape_hash                 varchar not null,
  constraint ck_query_plan_change_change_type check ( change_type in ('FIRST','CHANGED')),
  constraint ix_query_plan_change_to unique (to_plan_id),
  constraint pk_query_plan_change primary key (id)
);

-- foreign keys and indices
create index if not exists ix_query_plan_change_series on ebean_insight.query_plan_change (app_id,env_id,hash,when_captured);
create index if not exists ix_query_plan_change_detected on ebean_insight.query_plan_change (detected_at);
create index if not exists ix_query_plan_change_notified on ebean_insight.query_plan_change (notified_at);
