name: GraalVM Native Image builds
on: [workflow_dispatch] ##, push, pull_request]
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
#        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Maven version
        run: mvn --version

      - name: Native image version
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

#      - name: Build with Maven
#        run: mvn clean package -Pnative

      - name: Build with Maven
        run:   |
          if [ "$RUNNER_OS" == "Linux" ]; then
               mvn clean package -Pnative,linux
          else
               mvn clean package -Pnative,mac -DskipTests
          fi

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ebean-insight-${{ matrix.os }}
          path: target/ebean-insight*
