name: GraalVM Native Image builds
on: [workflow_dispatch] ##, push, pull_request]
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [macos-latest, ubuntu-latest]
        os: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: maven version
        run: mvn --version

      - name: ldd (glibc) version
        run: ldd --version

      - name: native image version
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build with Maven
        run:   |
          if [ "$RUNNER_OS" == "Linux" ]; then
               mvn clean package -Pnative
          else
               mvn clean package -Pnative,mac -DskipTests
          fi

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ebean-insight-${{ matrix.os }}
          path: target/ebean-insight*
